// <auto-generated />
using System;
using Huby.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Huby.Migrations
{
    [DbContext(typeof(ApplicationDatabase))]
    [Migration("20200723193011_IdStringLengthCreate")]
    partial class IdStringLengthCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Huby.Data.Follower", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(12)")
                        .HasMaxLength(12);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FollowerUserId")
                        .IsRequired()
                        .HasColumnType("character varying(12)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.HasIndex("FollowerUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("Huby.Data.Hub", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(12)")
                        .HasMaxLength(12);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Hubs");
                });

            modelBuilder.Entity("Huby.Data.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Dislikes")
                        .HasColumnType("integer");

                    b.Property<string>("IsNSFW")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("character varying(12)");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Posts");

                    b.HasDiscriminator<string>("PostType").HasValue("Post");
                });

            modelBuilder.Entity("Huby.Data.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(12)")
                        .HasMaxLength(12);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HubId")
                        .IsRequired()
                        .HasColumnType("character varying(12)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Huby.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(12)")
                        .HasMaxLength(12);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Huby.Data.Comment", b =>
                {
                    b.HasBaseType("Huby.Data.Post");

                    b.Property<string>("ParentId")
                        .HasColumnType("character varying(12)");

                    b.HasIndex("ParentId");

                    b.HasDiscriminator().HasValue("Comment");
                });

            modelBuilder.Entity("Huby.Data.Topic", b =>
                {
                    b.HasBaseType("Huby.Data.Post");

                    b.Property<string>("HubId")
                        .IsRequired()
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasIndex("HubId");

                    b.HasDiscriminator().HasValue("Topic");
                });

            modelBuilder.Entity("Huby.Data.Follower", b =>
                {
                    b.HasOne("Huby.Data.User", "FollowerUser")
                        .WithMany()
                        .HasForeignKey("FollowerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Huby.Data.User", "User")
                        .WithMany("Followers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Huby.Data.Hub", b =>
                {
                    b.HasOne("Huby.Data.User", "Owner")
                        .WithMany("Hubs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Huby.Data.Post", b =>
                {
                    b.HasOne("Huby.Data.User", "Owner")
                        .WithMany("Posts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Huby.Data.Subscription", b =>
                {
                    b.HasOne("Huby.Data.Hub", "Hub")
                        .WithMany("Subscribers")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Huby.Data.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Huby.Data.Comment", b =>
                {
                    b.HasOne("Huby.Data.Post", "Parent")
                        .WithMany("Comments")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Huby.Data.Topic", b =>
                {
                    b.HasOne("Huby.Data.Hub", "Hub")
                        .WithMany("Topics")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
